//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SVSistema
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pazimys6
    {
        public int ID { get; set; }
        public int Dalyko_ID { get; set; }
        public int Studento_ID { get; set; }
        public int Ivertinimas { get; set; }
        public string Komentaras { get; set; }
        public Nullable<int> Destytojo_ID { get; set; }
    
        public virtual Dalykas7 Dalykas7 { get; set; }
        public virtual Studentas6 Studentas6 { get; set; }
    }
}
