//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SVSistema
{
    using System;
    using System.Collections.Generic;
    
    public partial class SVSAdmin
    {
        public int Id { get; set; }
        public string Prisijungimo_Vardas { get; set; }
        public string Slaptazodis { get; set; }
    }
}
